<?php

/**
 * @file
 * Provides S3 stream wrapper
 */

/**
 * Implements hook_stream_wrappers().
 *
 * Create a stream wrapper for S3
 */
function amazons3_stream_wrappers() {
  return array(
    's3' => array(
      'name' => 'Amazon S3',
      'class' => 'AmazonS3StreamWrapper',
      'description' => t('Amazon Simple Storage Service'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function amazons3_menu() {
  $items = array();

  $items['admin/config/media/amazons3'] = array(
    'title' => 'Amazon S3',
    'description' => 'Configure your S3 credentials',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('amazons3_admin'),
    'access arguments' => array('access administration pages'),
  );
  
  return $items;
}

/**
 * Implements hook_help().
 */
function amazons3_help($path, $arg) {
  switch ($path) {
    case 'admin/config/media/amazons3':
    if (module_exists('awssdk_ui')) {
      return '<p>' . t('Amazon Web Services authentication can be configured at the <a href="@awssdk_config">AWS SDK configuration page</a>.', array('@awssdk_config' => url('admin/config/media/awssdk'))) . '</p>';
    }
    else {
      return '<p>' . t('Enable \'AWS SDK for PHP UI\' module to configure your Amazon Web Services authentication. Configuration can also be defined in the $conf array in settings.php.', array('@awssdk_config' => url('admin/config/media/awssdk'))) . '</p>';
    }
  }
}

/**
 * Implements hook_admin().
 */
function amazons3_admin() {
  $form = array();
  
  $form['amazons3_bucket'] = array(
      '#type'           => 'textfield',
      '#title'          => t('Default Bucket Name'),
      '#default_value'  => variable_get('amazons3_bucket', ''),
      '#required'       => TRUE,
  );
  
  $form['amazons3_cname'] = array(
    '#type'           => 'checkbox',
    '#title'          => t('Enable CNAME'),
    '#description'    => t('Checking this box will use the above bucket name as the URL to serve files from e.g. the bucket would be named "mybucket.mydomain.com"'),
    '#default_value'  => variable_get('amazons3_cname', 0),
  );
  
  return system_settings_form($form);
}

function amazons3_admin_validate($form, &$form_state) {
  $bucket = $form_state['values']['amazons3_bucket'];
  $key = variable_get('aws_key', '');
  $secret_key = variable_get('aws_secret_key', '');
  
  if(!libraries_load('awssdk')) {
    form_set_error('amazons3_bucket', t('Unable to load the AWS SDK. Please check you have installed the library correctly and configured your S3 credentials.'));
  }
  else {
    try {
      $s3 = new AmazonS3($key, $secret_key);
      // test connection
      $user_id = $s3->get_canonical_user_id();
      if(!$user_id['id']) {
        form_set_error('amazons3_bucket', t('The S3 access credentials are invalid'));
      }
      else if(!$s3->if_bucket_exists($bucket)) {
        form_set_error('amazons3_bucket', t('The bucket does not exist'));
      }
    }
    catch(RequestCore_Exception $e){
      if(strstr($e->getMessage(), 'SSL certificate problem')) {
        form_set_error('amazons3_bucket', t('There was a problem with the SSL certificate. Try setting AWS_CERTIFICATE_AUTHORITY to true in libraries/awssdk/config.inc.php'));  
      }
      else {
        form_set_error('amazons3_bucket', t('There was a problem connecting to S3'));  
      }
      
    }
    catch(Exception $e) {
      form_set_error('amazons3_bucket', t('There was a problem using S3'));
    }
  }
}

function amazons3_image_style_flush($style) {
  // Empty cached data that contains information about the style.
  if(isset($style->old_name) && strlen($style->old_name) > 0) {
    drupal_rmdir('s3://styles/' . $style->old_name);  
  }
  if(isset($style->name) && strlen($style->name) > 0) {
    drupal_rmdir('s3://styles/' . $style->name);  
  }
}