<?php

/**
 * @file
 * Provides S3 stream wrapper
 */

/**
 * Implements hook_stream_wrappers().
 *
 * Create a stream wrapper for S3
 */
function media_amazon_stream_wrappers() {
  return array(
    's3' => array(
      'name' => 'Amazon S3',
      'class' => 'MediaAmazonS3StreamWrapper',
      'description' => t('Amazon Simple Storage Service'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function media_amazon_menu() {
  $items = array();

  $items['admin/config/media/amazon'] = array(
    'title' => 'Amazon Web Services',
    'description' => 'Configure your S3 credentials',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_amazon_admin'),
    'access arguments' => array('access administration pages'),
  );
  
  return $items;
}

/**
 * Implements hook_admin().
 */
function media_amazon_admin() {
  $form = array();
  
  $form['media_amazon_s3_bucket'] = array(
      '#type'           => 'textfield',
      '#title'          => t('Bucket Name'),
      '#default_value'  => variable_get('media_amazon_s3_bucket', ''),
      '#required'       => TRUE,
  );
  
  $form['media_amazon_key'] = array(
      '#type'           => 'textfield',
      '#title'          => t('Access Key ID'),
      '#default_value'  => variable_get('media_amazon_key', ''),
      '#required'       => TRUE,
  );
  
  $form['media_amazon_key_secret'] = array(
      '#type'           => 'password',
      '#title'          => t('Secret Access Key'),
      '#default_value'  => variable_get('media_amazon_key_secret', ''),
      '#required'       => TRUE,
  );
  
  return system_settings_form($form);
}

/**
 * Implements hook_url_outbound_alter().
 */
function media_amazon_url_outbound_alter(&$path, &$options, $original_path) {
  $style_path = variable_get('media_amazon_s3_bucket', '') . '.s3.amazonaws.com/styles/';
  // strip protocol
  $path_no_protocol = str_replace(array('http://', 'https://'), '', $path);
  if(substr($path_no_protocol, 0, strlen($style_path)) == $style_path) {
    $style_path_fragment = substr($path_no_protocol, strlen($style_path));
    // deliver the image through the private file system
    // also creates derivative on S3 at the same time
    $path = url('system/files/styles/' . $style_path_fragment);
  }
}
