<?php

/**
 * @file
 * Provides S3 stream wrapper
 */

/**
 * Create a stream wrapper for S3
 */
function media_amazon_stream_wrappers() {
  return array(
    's3' => array(
      'name' => 'Amazon S3',
      'class' => 'MediaAmazonS3StreamWrapper',
      'description' => t('Amazon Simple Storage Service'),
    ),
  );
}

function media_amazon_menu() {
  $items = array();

  $items['admin/config/media/amazon'] = array(
    'title' => 'Amazon Web Services',
    'description' => 'Configure your S3 credentials',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_amazon_admin'),
    'access arguments' => array('access administration pages'),
  );
  
  return $items;
}

function media_amazon_admin() {
  $form = array();
  
  $form['media_amazon_s3_bucket'] = array(
      '#type'           => 'textfield',
      '#title'          => t('Bucket Name'),
      '#default_value'  => variable_get('media_amazon_s3_bucket', ''),
      '#required'       => TRUE,
  );
  
  $form['media_amazon_key'] = array(
      '#type'           => 'textfield',
      '#title'          => t('Access Key ID'),
      '#default_value'  => variable_get('media_amazon_key', ''),
      '#required'       => TRUE,
  );
  
  $form['media_amazon_key_secret'] = array(
      '#type'           => 'password',
      '#title'          => t('Secret Access Key'),
      '#default_value'  => variable_get('media_amazon_key_secret', ''),
      '#required'       => TRUE,
  );
  
  return system_settings_form($form);
}

/**
 * Implements hook_url_outbound_alter().
 */
function media_amazon_url_outbound_alter(&$path, &$options, $original_path) {
  $style_url = 'http://' . variable_get('media_amazon_s3_bucket', '') . '.s3.amazonaws.com/styles/';
  if(substr($path, 0, strlen($style_url)) == $style_url) {
    if(!_media_amazon_style_exists($path)) {
      // queue image to be uploaded
      $queue = DrupalQueue::get('media_amazon_styles');
      if(!$queue->createItem($path)) {
        watchdog();
      }
      // deliver it through the private file system for now
      $path = '/system/files/styles/' . substr($path, strlen($style_url));
    }
  }
}

function _media_amazon_style_exists($uri) {
  $query = db_select('media_amazon_styles', 'm');
  $query
    ->condition('m.uri', $uri, '=')
    ->fields('m');
  $result = $query->countQuery()->execute()->fetchField();
  return $result;
}

function media_amazon_cron() {
  $queue = DrupalQueue::get('media_amazon_styles');
}

function media_amazon_cron_queue_info() {
  $queues['media_amazon_styles'] = array(
    'worker callback' => '_media_amazon_styles_upload',
    'time' => 60,
  );
}

/**
 * Processes images and uploads them to Amazon S3
 *
 * @param $path
 * The intended path for the generated object.
 * This will also contain the style information.
 */
 
function _media_amazon_styles_upload($path) {
  
}